### ISSUE TITLE
Unable to pull the image

### ISSUE THREAD

**Issue by vamsidvk09** [iadvize/traefik-exporter#1]
Please answer these questions before submitting your issue. Thanks!
I tried to pull the image from docker hub. It's not available through UI as well. Please help with that

**Comment by samber** [comment]
Hi @vamsidvk09 

This exporter is deprecated !!
It won't work with modern version of Traefik ;)

You should check that => https://docs.traefik.io/configuration/metrics/

**Comment by vamsidvk09** [comment]
Thanks for the update. Will check out the link
